### ISSUE TITLE
ProDJ Link support for CDJ1000 New life?

### ISSUE THREAD

**Issue by mdethmers** [djgreeb/Sampler-DJS-500#1]
hey man, im super impressed by what you are able to achieve with all this reverse engineering from pioneer equipment. also very impressed with your ProDJ link support. 

As you are using the same Discovery board for the sampler as you do for the CDJ1000 mod, do you say it would be possible to support ProDJ link support to the cdj1000 firmware? I have two of those cdj1000 NL players, and with prodj link support, it would be possible to sync bpm with my xdj700 players!

is it a matter of copy-pasting the sampler firmware over to the cdj firmware? if you want to share your code I might be able to figure it our myself and update you once I have a working copy :)

**Comment by djgreeb** [comment]
Hey! I think that the CDJ-1000mk3 project, on the 32F746G board, will not be able to support prodj link with full compliance with the standard. Some of the gpio pins that are needed for ETH-PHY are already involved there. There is also too little memory on the board. 
If you want to connect 2 cdj-1000mk3, based on 32F746G and you do not need to connect them to CDJ-2000s and send files, you can connect the players using uart for synchronization. 
I'll add the sampler source code later.
