### ISSUE TITLE
Remove Pioneer Branding

### ISSUE THREAD

**Issue by terdinatore** [djgreeb/Sampler-DJS-500#2]
Hey Andrei,

I do really love what you do with this project. 

I would like to suggest removing all the Pioneer branding since it could provoke legal action from AlphaTheta Corp. and prevent you from continuing working on this in the future.

Best regards,

**Comment by djgreeb** [comment]
Hi. Thank you! Where do you propose to remove the brand? On the hull? from the firmware source codes? I don't plan to make any more instances of the sampler. And I made mine with such a brand with style that my setup looked like one (cdj-2000nxs and djm-900nxs). I have no plans to compete with Pioneer Dj or hurt their business in any way. Those wishing to make the same sampler do not need to repeat all the inscriptions on the device.

**Comment by terdinatore** [comment]
I am no lawyer, but in my humble opinion you should be fine having your personal sampler using any design you like.

What I would remove:
- No videos from your personal units that show the Pioneer livery. 
- Remove Pioneer Logos from Firmware
- Remove/Edit any Photographs in this repo showing the Pioneer logo on the device.

While I wish such incredible DJ gear existed and Pioneer would see this and get inspired, I hope that they don't see it and set their attorneys on you.
